version: '3.8'

services:
  test-linux:
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile.archlinux
    volumes:
      - ../../.docker/linux:/home/docker/scripts:rw
      - ./run-tests.sh:/home/docker/run-tests.sh:ro
    working_dir: /home/docker/scripts
    command: ["bash", "/home/docker/run-tests.sh"]

  test-darwin:
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile.darwin
    volumes:
      - ../../.docker/darwin:/home/docker/scripts:rw
      - ./run-tests.sh:/home/docker/run-tests.sh:ro
    working_dir: /home/docker/scripts
    command: ["bash", "/home/docker/run-tests.sh"] 