version: '3.8'

services:
  test-linux:
    build:
      context: .
      dockerfile: Dockerfile.archlinux
    volumes:
      - ../../:/home/docker/scripts:rw
      - ./run-tests.sh:/home/docker/run-tests.sh:ro
    working_dir: /home/docker/scripts
    command: ["bash", "/home/docker/run-tests.sh"]

  test-darwin:
    build:
      context: .
      dockerfile: Dockerfile.darwin
    volumes:
      - ../../:/home/docker/scripts:rw
      - ./run-tests.sh:/home/docker/run-tests.sh:ro
    working_dir: /home/docker/scripts
    command: ["bash", "/home/docker/run-tests.sh"] 